print("1. In a print statement, what happens if you leave out one of the parentheses,or both? \n  it will shows an error")
print("******************************")
print("2. If you are trying to print a string, what happens if you leave out one of the quotation marks,or both? \n it will shows error that the string is not defined if u leave out both, and if u leave one it will shows syntax error ")
print("******************************")
print("3. You can use a minus sign to make a negative number like -2. What happens if you put a plus sign before a number? What about 2++2? \n if we print -2 for example it will print -2 \n if we print +2 it will print 2 \n if we print 2++2 it will print 4 ")
print("******************************")
print("4. In math notation, leading zeros are ok, as in 09. What happens if you try this in Python? What about 011? /n  it will give syntax error")
print("******************************")
print("5. What happens if you have two values with no operator between them? \n  error if we print(2 2) but if we print(22) it will consider them as one value")
